### PR TITLE
Added winget releaser PR workflow with new version

### PR DESCRIPTION
**Pull request by schembriaiden**
## Do not post the secret here

As explained by the title this will start automatically creating winget manifests for you when a new version is published on GitHub.

A few things are needed, so follow these steps or else the workflow will not run:

1. Go on your ManiArasteh account and go to your account settings from the top-right:

image

2. Bottom-left go to `Developer Settings`

image

3. Then go to `Personal Access Tokens` and then `Tokens (classic)`:

image

4. Then click `Generate new-token`, and go on `Generate new token (classic)`:

image

5. Here as Note put: `BeagleSoftware Winget Releaser`, Expiration set it to `No Expiration` (If you want to create an expiration date go ahead, but this would mean repeating this process at the end of its lifetime), and scope select the following:

image

Then just scroll down and hit `Generate token`, after just copy the token and keep it handy

6. Then come back to this repository on the beaglesoftware account, or an account that has permissions to access settings on it, and click `Settings`:

image

7. Then go to `Secrets and Variables` and click on `Actions`:

image

8. Then click `New repository secret:

image

9. Name should be: WINGET_TOKEN and Secret should be the one you copied from before, then just click `Add Secret`

### CODE REVIEW

**Comment by ManiArasteh** [comment]
Aha, thanks!

**Comment by schembriaiden** [comment]
I don't think there was really an issue with this workflow, its just that for some reason it ran with the merge which it shouldn't it should only run when you create a new release

**Comment by ManiArasteh** [comment]
I tested two-three days ago.

**Comment by schembriaiden** [comment]
It wouldn't have worked back then due to the manifest not being merged yet:

image

**Comment by ManiArasteh** [comment]
Ok :+1:

**Pull request merged**
